default:
  image:
    name:
      ghcr.io/queensberry-research/docker:0.3.5
      # docker-registry.main:5000/ci:0.3.23
    docker:
      platform: linux/amd64
  interruptible: true

stages:
  - main
  - publish

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .venv/
  GIT_DEPTH: 1
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_SUBMODULE_STRATEGY: recursive

.stage--pr-only:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  stage: main

.stage--pr-or-sched:
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master") || $CI_PIPELINE_SOURCE == "schedule"'
  stage: main

.stage--publish:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  stage: publish

.uv:
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  variables:
    UV_CACHE_DIR: .uv-cache
    UV_LINK_MODE: copy
  after_script:
    - uv cache prune --ci

.uv-build:
  script:
    - uv build --wheel

.uv-run-pytest:
  script:
    - |
      if [ -n "$DEBUG_PYTEST" ]; then
        echo "Sleeping for $DEBUG_PYTEST..." && sleep "$DEBUG_PYTEST"
      fi
    - uv run pytest -n=auto

.uv-sync:
  before_script:
    - uv sync --all-extras

# ---- main -------------------------------------------------------------------

ruff:
  extends:
    - .stage--pr-or-sched
    - .uv
    - .uv-sync
  script:
    - |
      if [ -n "$DEBUG_RUFF" ]; then
        echo "Sleeping for $DEBUG_RUFF..." && sleep "$DEBUG_RUFF"
      fi
    - uv run ruff check .
    - uv run ruff format --check .

pyright:
  extends:
    - .stage--pr-or-sched
    - .uv
    - .uv-sync
  script:
    - |
      if [ -n "$DEBUG_PYRIGHT" ]; then
        echo "Sleeping for $DEBUG_PYRIGHT..." && sleep "$DEBUG_PYRIGHT"
      fi
    - uv run pyright

pytest-highest:
  extends:
    - .stage--pr-or-sched
    - .uv
    - .uv-sync
  script:
    - !reference [.uv-run-pytest, script]

pytest-lowest-direct:
  extends:
    - .stage--pr-or-sched
    - .uv
  before_script:
    - uv sync --all-extras  --resolution=lowest-direct
  script:
    - !reference [.uv-run-pytest, script]

build:
  extends:
    - .stage--pr-or-sched
    - .uv
  script:
    - |
      if [ -n "$DEBUG_BUILD" ]; then
        echo "Sleeping for $DEBUG_BUILD..." && sleep "$DEBUG_BUILD"
      fi
    - !reference [.uv-build, script]

publish-pypi:
  extends:
    - .stage--publish
    - .uv
  script:
    - |
      if [ -n "$DEBUG_PUBLISH_PYPI" ]; then
        echo "Sleeping for $DEBUG_PUBLISH_PYPI..." && sleep "$DEBUG_PUBLISH_PYPI"
      fi
    - !reference [.uv-build, script]
    - uv publish

publish-docker:
  extends:
    - .stage--publish
  rules:
    - exists:
        - docker/Dockerfile
  script:
    - |
      if [ -n "$DEBUG_PUBLISH_DOCKER" ]; then
        echo "Sleeping for $DEBUG_PUBLISH_DOCKER..." && sleep "$DEBUG_PUBLISH_DOCKER"
      fi
    - . .env
    - PACKAGE_VERSION=$(bump-my-version show current_version)
    - PACKAGE_VERSION_MAJOR=$(echo "$PACKAGE_VERSION" | cut -d. -f1)
    - PACKAGE_VERSION_MAJOR_MINOR=$(echo "$PACKAGE_VERSION" | cut -d. -f1,2)
    - PACKAGE_NAME=$(yq '.project.name' pyproject.toml)
    - |
      if yq --exit-status --input-format toml --output-format yaml \
        '.project."optional-dependencies".scripts' pyproject.toml >/dev/null 2>&1; then
        export PACKAGE_HAS_SCRIPTS=1
      else
        export PACKAGE_HAS_SCRIPTS=0
      fi
    - |
      docker buildx build \
        --build-arg DEBIAN_VERSION=$DEBIAN_VERSION \
        --build-arg PYTHON_VERSION=$PYTHON_VERSION \
        --build-arg PACKAGE_NAME=$PACKAGE_NAME \
        --build-arg PACKAGE_HAS_SCRIPTS=$PACKAGE_HAS_SCRIPTS \
        --file docker/Dockerfile \
        --push \
        --tag $DOCKER_REGISTRY_URL:$DOCKER_REGISTRY_PORT/$PACKAGE_NAME:latest \
        --tag $DOCKER_REGISTRY_URL:$DOCKER_REGISTRY_PORT/$PACKAGE_NAME:$PACKAGE_VERSION \
        --tag $DOCKER_REGISTRY_URL:$DOCKER_REGISTRY_PORT/$PACKAGE_NAME:$PACKAGE_VERSION_MAJOR \
        --tag $DOCKER_REGISTRY_URL:$DOCKER_REGISTRY_PORT/$PACKAGE_NAME:$PACKAGE_VERSION_MAJOR_MINOR \
        .
