default_install_hook_types: [pre-commit, pre-push]

repos:
  # fixers
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-lock
        args: [--upgrade]
  - repo: https://github.com/compwa/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args:
          [
            --option,
            indent_tables=true,
            --option,
            indent_entries=true,
            --option,
            reorder_keys=true,
          ]
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.13.23
    hooks:
      - id: check-submodules-updated
        args: [--run-every=PT5M]
      - id: check-version-bumped
      - id: format-requirements
      - id: mirror-files
        args: [repo/git/.gitignore, .gitignore, --run-every=PT5M]
      - id: replace-sequence-str
      - id: run-bump-my-version
        args: [--mode=bumpversion]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
  # linters
  # - repo: https://github.com/andreoliwa/nitpick
  #   rev: v0.37.0
  #   hooks:
  #     - id: nitpick-check
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
  # fixers/linters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: system
        types_or: [markdown, yaml]
