extend = "repo/ruff/ruff.toml"

[lint]
  exclude = ["src/public/installer"]
  extend-ignore = [
    "TID252", # relative-imports
  ]

  [lint.flake8-bugbear]
    extend-immutable-calls = [
      "public.utilities.field_df",
      "public.utilities.toml_bool",
      "public.utilities.toml_path",
      "public.utilities.toml_str",
      "public.utilities.toml_strs",
    ]
