target-version = "py311"
unsafe-fixes = true

[format]
preview = true
skip-magic-trailing-comma = true

[lint]
explicit-preview-rules = true
fixable = ["ALL"]
ignore = [
  "D",
  "C901",  # complex-structure
  "COM812",  # missing-trailing-comma
  "PLR0912",  # too-many-branches
  "PLR2004",  # magic-value-comparison
  "S",
]
preview = true
select = ["ALL"]

[lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false
