services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION:?}
        PYTHON_VERSION: ${PYTHON_VERSION:?}
        PACKAGE_NAME_UNDERSCORE: ${PACKAGE_NAME_UNDERSCORE:?}
        PACKAGE_HAS_SCRIPTS: ${PACKAGE_HAS_SCRIPTS:?}
    container_name: ${PACKAGE_NAME:?}
    environment:
      SOPS_AGE_KEY_FILE: /run/secrets/age_key.txt
    restart: always
    secrets:
      - age_key.txt
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

secrets:
  age_key.txt:
    file: ~/.config/sops/age/keys.txt
