[dir]
  content = ["backup", "iso", "vztmpl"]
  name = "local"
  path = "/var/lib/vz"

[nfs]
  content = [
    "backup",
    "images",
    "import",
    "iso",
    "rootdir",
    "snippets",
    "vztmpl",
  ]
  export = "/mnt/qrt-pool/qrt-dataset"
  mount_point = "/mnt/qrt-share"
  name = "qrt-share"
  nodes = ["proxmox"]
  path = "/mnt/pve/qrt-share"
  server = "truenas.qrt"

[zfspool]
  content = ["images", "rootdir"]
  name = "local-zfs"
  pool = "rpool/data"
  sparse = true
