from __future__ import annotations

from .installer_constants import (
    AUTHORIZED_KEYS,
    BASHRC,
    CONFIG_BOTTOM_TOML,
    CONFIG_DIRENV,
    CONFIG_FD_IGNORE,
    CONFIG_FISH,
    CONFIG_FISH_CONF_D,
    CONFIG_FISH_FUNCTIONS,
    CONFIG_GIT,
    CONFIG_GLAB_CONFIG_YML,
    CONFIG_NVIM,
    CONFIG_SOPS_AGE,
    CONFIG_STARSHIP_TOML,
    CONFIG_TMUX,
    CONFIG_TMUX_CONF_LOCAL,
    CONFIG_TMUX_CONF_OH_MY_TMUX,
    CONFIG_WEZTERM_LUA,
    ETC,
    HOME,
    KNOWN_HOSTS,
    LOCAL_BIN,
    PDBRC,
    PSQLRC,
    RESOLV_CONF,
    SSH,
    SSH_CONFIG,
    SSH_CONFIG_D,
    XDG_CONFIG_HOME,
)

BASHRC_D__SUBNET_SH = HOME / ".bashrc.d/subnet.sh"
HOME_INFRA = HOME / "infra"
HOME_PUBLIC = HOME / "public"
PVE = ETC / "pve"
SSH_INFRA = SSH / "infra"


PVE_STORAGE_CFG = PVE / "storage.cfg"


__all__ = [
    "AUTHORIZED_KEYS",
    "BASHRC",
    "BASHRC_D__SUBNET_SH",
    "CONFIG_BOTTOM_TOML",
    "CONFIG_DIRENV",
    "CONFIG_FD_IGNORE",
    "CONFIG_FISH",
    "CONFIG_FISH_CONF_D",
    "CONFIG_FISH_FUNCTIONS",
    "CONFIG_GIT",
    "CONFIG_GLAB_CONFIG_YML",
    "CONFIG_NVIM",
    "CONFIG_SOPS_AGE",
    "CONFIG_STARSHIP_TOML",
    "CONFIG_TMUX",
    "CONFIG_TMUX_CONF_LOCAL",
    "CONFIG_TMUX_CONF_OH_MY_TMUX",
    "CONFIG_WEZTERM_LUA",
    "ETC",
    "HOME",
    "HOME_INFRA",
    "HOME_PUBLIC",
    "KNOWN_HOSTS",
    "LOCAL_BIN",
    "PDBRC",
    "PSQLRC",
    "PVE",
    "PVE_STORAGE_CFG",
    "RESOLV_CONF",
    "SSH",
    "SSH_CONFIG",
    "SSH_CONFIG_D",
    "SSH_INFRA",
    "XDG_CONFIG_HOME",
]
